# Even Fibonacci numbers
## Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [84]:
%%time
def fib_gen():
    g,p = 2,1
    while p<=4000000:
        yield p
        g, p = g+p, g


solution = 0
for f in fib_gen():
    if f%2==0:
        solution += f

solution

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 31.9 µs

4613732

In [85]:
%%time
def compute():
	ans = 0
	x = 1  # Represents the current Fibonacci number being processed
	y = 2  # Represents the next Fibonacci number in the sequence
	while x <= 4000000:
		if x % 2 == 0:
			ans += x
		x, y = y, x + y
	return str(ans)

compute()

CPU times: user 26 µs, sys: 0 ns, total: 26 µs
Wall time: 30.3 µs

'4613732'

[3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887]

2
2
3
3
3
5
5
5
8
8
8
13
13
13
21
21
21
34
34
34
55
55
55
89
89
89
144

In [5]:
a

3

In [6]:
b

1